// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3XBH5FyuVxKO9UUHmAoZ3OqHvTkaiAo',
    appId: '1:552303419424:web:a9a8630fd1551647455c45',
    messagingSenderId: '552303419424',
    projectId: 'kvu-shopping-app',
    authDomain: 'kvu-shopping-app.firebaseapp.com',
    storageBucket: 'kvu-shopping-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLHv6i65_op3fuygr-LYNCzl2gRSziY0',
    appId: '1:552303419424:android:53f54ed119473844455c45',
    messagingSenderId: '552303419424',
    projectId: 'kvu-shopping-app',
    storageBucket: 'kvu-shopping-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsHqbur2kyUtla72CtIYRn2GVhDXl_yc',
    appId: '1:552303419424:ios:2d281d97b90df2bf455c45',
    messagingSenderId: '552303419424',
    projectId: 'kvu-shopping-app',
    storageBucket: 'kvu-shopping-app.appspot.com',
    iosClientId: '552303419424-hrfr5gr73ehtgbfq48bh9tsqia5176cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsHqbur2kyUtla72CtIYRn2GVhDXl_yc',
    appId: '1:552303419424:ios:2d281d97b90df2bf455c45',
    messagingSenderId: '552303419424',
    projectId: 'kvu-shopping-app',
    storageBucket: 'kvu-shopping-app.appspot.com',
    iosClientId: '552303419424-hrfr5gr73ehtgbfq48bh9tsqia5176cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
